{"trial_id": "0001", "hyperparameters": {"space": [{"class_name": "Int", "config": {"name": "units", "default": null, "conditions": [], "min_value": 32, "max_value": 512, "step": 32, "sampling": "linear"}}, {"class_name": "Choice", "config": {"name": "learning_rate", "default": 0.01, "conditions": [], "values": [0.01, 0.001, 0.0001], "ordered": true}}, {"class_name": "Choice", "config": {"name": "nodes", "default": 0.0, "conditions": [], "values": [0.0, 0.1, 0.2, 0.3], "ordered": true}}, {"class_name": "Choice", "config": {"name": "recurrent_droput", "default": 0.0, "conditions": [], "values": [0.0, 0.1, 0.2, 0.3], "ordered": true}}], "values": {"units": 256, "learning_rate": 0.01, "nodes": 0.2, "recurrent_droput": 0.3, "tuner/epochs": 2, "tuner/initial_epoch": 0, "tuner/bracket": 2, "tuner/round": 0}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"/Users/dixonb01/.pyenv/versions/3.9.11/lib/python3.9/site-packages/keras_tuner/engine/base_tuner.py\", line 270, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"/Users/dixonb01/.pyenv/versions/3.9.11/lib/python3.9/site-packages/keras_tuner/engine/base_tuner.py\", line 261, in _run_and_update_trial\n    tuner_utils.convert_to_metrics_dict(\n  File \"/Users/dixonb01/.pyenv/versions/3.9.11/lib/python3.9/site-packages/keras_tuner/engine/tuner_utils.py\", line 225, in convert_to_metrics_dict\n    [convert_to_metrics_dict(elem, objective) for elem in results]\n  File \"/Users/dixonb01/.pyenv/versions/3.9.11/lib/python3.9/site-packages/keras_tuner/engine/tuner_utils.py\", line 225, in <listcomp>\n    [convert_to_metrics_dict(elem, objective) for elem in results]\n  File \"/Users/dixonb01/.pyenv/versions/3.9.11/lib/python3.9/site-packages/keras_tuner/engine/tuner_utils.py\", line 238, in convert_to_metrics_dict\n    best_value, _ = _get_best_value_and_best_epoch_from_history(\n  File \"/Users/dixonb01/.pyenv/versions/3.9.11/lib/python3.9/site-packages/keras_tuner/engine/tuner_utils.py\", line 209, in _get_best_value_and_best_epoch_from_history\n    objective_value = objective.get_value(metrics)\n  File \"/Users/dixonb01/.pyenv/versions/3.9.11/lib/python3.9/site-packages/keras_tuner/engine/objective.py\", line 57, in get_value\n    return logs[self.name]\nKeyError: 'val_accuracy'\n"}